In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/drive/MyDrive/home_insurance.csv/home_insurance.csv")

In [4]:
df.shape

(256136, 66)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256136 entries, 0 to 256135
Data columns (total 66 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   QUOTE_DATE              129524 non-null  object
 1   COVER_START             189021 non-null  object
 2   CLAIM3YEARS             190039 non-null  object
 3   P1_EMP_STATUS           189021 non-null  object
 4   P1_PT_EMP_STATUS        1782 non-null    object
 5   BUS_USE                 189021 non-null  object
 6   CLERICAL                2944 non-null    object
 7   AD_BUILDINGS            189021 non-null  object
 8   RISK_RATED_AREA_B       140876 non-null  float64
 9   SUM_INSURED_BUILDINGS   189021 non-null  float64
 10  NCD_GRANTED_YEARS_B     189021 non-null  float64
 11  AD_CONTENTS             189021 non-null  object
 12  RISK_RATED_AREA_C       180290 non-null  float64
 13  SUM_INSURED_CONTENTS    189021 non-null  float64
 14  NCD_GRANTED_YEARS_C     189021 non-null  float64
 15  CONTENTS_COVER          189021 non-null  object
 16  BUILDINGS_COVER         189021 non-null  object
 17  SPEC_SUM_INSURED        189021 non-null  float64
 18  SPEC_ITEM_PREM          189021 non-null  float64
 19  UNSPEC_HRP_PREM         189021 non-null  float64
 20  P1_DOB                  189021 non-null  object
 21  P1_MAR_STATUS           189021 non-null  object
 22  P1_POLICY_REFUSED       189021 non-null  object
 23  P1_SEX                  189021 non-null  object
 24  APPR_ALARM              189021 non-null  object
 25  APPR_LOCKS              189021 non-null  object
 26  BEDROOMS                189021 non-null  float64
 27  ROOF_CONSTRUCTION       189021 non-null  float64
 28  WALL_CONSTRUCTION       189021 non-null  float64
 29  FLOODING                189021 non-null  object
 30  LISTED                  189021 non-null  float64
 31  MAX_DAYS_UNOCC          189021 non-null  float64
 32  NEIGH_WATCH             189021 non-null  object
 33  OCC_STATUS              189021 non-null  object
 34  OWNERSHIP_TYPE          189021 non-null  float64
 35  PAYING_GUESTS           189021 non-null  float64
 36  PROP_TYPE               189021 non-null  float64
 37  SAFE_INSTALLED          189021 non-null  object
 38  SEC_DISC_REQ            189021 non-null  object
 39  SUBSIDENCE              189021 non-null  object
 40  YEARBUILT               189021 non-null  float64
 41  CAMPAIGN_DESC           0 non-null       float64
 42  PAYMENT_METHOD          189021 non-null  object
 43  PAYMENT_FREQUENCY       80554 non-null   float64
 44  LEGAL_ADDON_PRE_REN     189021 non-null  object
 45  LEGAL_ADDON_POST_REN    189021 non-null  object
 46  HOME_EM_ADDON_PRE_REN   189021 non-null  object
 47  HOME_EM_ADDON_POST_REN  189021 non-null  object
 48  GARDEN_ADDON_PRE_REN    189021 non-null  object
 49  GARDEN_ADDON_POST_REN   189021 non-null  object
 50  KEYCARE_ADDON_PRE_REN   189021 non-null  object
 51  KEYCARE_ADDON_POST_REN  189021 non-null  object
 52  HP1_ADDON_PRE_REN       189021 non-null  object
 53  HP1_ADDON_POST_REN      189021 non-null  object
 54  HP2_ADDON_PRE_REN       189021 non-null  object
 55  HP2_ADDON_POST_REN      189021 non-null  object
 56  HP3_ADDON_PRE_REN       189021 non-null  object
 57  HP3_ADDON_POST_REN      189021 non-null  object
 58  MTA_FLAG                190039 non-null  object
 59  MTA_FAP                 55720 non-null   float64
 60  MTA_APRP                55720 non-null   float64
 61  MTA_DATE                26575 non-null   object
 62  LAST_ANN_PREM_GROSS     190039 non-null  float64
 63  POL_STATUS              189021 non-null  object
 64  i                       256136 non-null  int64
 65  Police                  256136 non-null  object
dtypes: float64(23), int64(1), object(42)
memory usage: 129.0+ MB

In [6]:
for column in df.columns:
  print(f"{column}:{df[column].dtype}")

QUOTE_DATE:object
COVER_START:object
CLAIM3YEARS:object
P1_EMP_STATUS:object
P1_PT_EMP_STATUS:object
BUS_USE:object
CLERICAL:object
AD_BUILDINGS:object
RISK_RATED_AREA_B:float64
SUM_INSURED_BUILDINGS:float64
NCD_GRANTED_YEARS_B:float64
AD_CONTENTS:object
RISK_RATED_AREA_C:float64
SUM_INSURED_CONTENTS:float64
NCD_GRANTED_YEARS_C:float64
CONTENTS_COVER:object
BUILDINGS_COVER:object
SPEC_SUM_INSURED:float64
SPEC_ITEM_PREM:float64
UNSPEC_HRP_PREM:float64
P1_DOB:object
P1_MAR_STATUS:object
P1_POLICY_REFUSED:object
P1_SEX:object
APPR_ALARM:object
APPR_LOCKS:object
BEDROOMS:float64
ROOF_CONSTRUCTION:float64
WALL_CONSTRUCTION:float64
FLOODING:object
LISTED:float64
MAX_DAYS_UNOCC:float64
NEIGH_WATCH:object
OCC_STATUS:object
OWNERSHIP_TYPE:float64
PAYING_GUESTS:float64
PROP_TYPE:float64
SAFE_INSTALLED:object
SEC_DISC_REQ:object
SUBSIDENCE:object
YEARBUILT:float64
CAMPAIGN_DESC:float64
PAYMENT_METHOD:object
PAYMENT_FREQUENCY:float64
LEGAL_ADDON_PRE_REN:object
LEGAL_ADDON_POST_REN:object
HOME_EM_ADDON_PRE_REN:object
HOME_EM_ADDON_POST_REN:object
GARDEN_ADDON_PRE_REN:object
GARDEN_ADDON_POST_REN:object
KEYCARE_ADDON_PRE_REN:object
KEYCARE_ADDON_POST_REN:object
HP1_ADDON_PRE_REN:object
HP1_ADDON_POST_REN:object
HP2_ADDON_PRE_REN:object
HP2_ADDON_POST_REN:object
HP3_ADDON_PRE_REN:object
HP3_ADDON_POST_REN:object
MTA_FLAG:object
MTA_FAP:float64
MTA_APRP:float64
MTA_DATE:object
LAST_ANN_PREM_GROSS:float64
POL_STATUS:object
i:int64
Police:object

In [7]:
df.describe()

,RISK_RATED_AREA_B,SUM_INSURED_BUILDINGS,NCD_GRANTED_YEARS_B,RISK_RATED_AREA_C,SUM_INSURED_CONTENTS,NCD_GRANTED_YEARS_C,SPEC_SUM_INSURED,SPEC_ITEM_PREM,UNSPEC_HRP_PREM,BEDROOMS,...,OWNERSHIP_TYPE,PAYING_GUESTS,PROP_TYPE,YEARBUILT,CAMPAIGN_DESC,PAYMENT_FREQUENCY,MTA_FAP,MTA_APRP,LAST_ANN_PREM_GROSS,i
count,140876.000000,189021.000000,189021.000000,180290.000000,189021.000000,189021.000000,189021.000000,189021.000000,189021.000000,189021.000000,...,189021.000000,189021.000000,189021.000000,189021.000000,0.0,80554.0,55720.000000,55720.000000,190039.000000,256136.000000
mean,10.274440,778130.472276,4.477132,9.055649,47836.219256,5.497336,329.517122,2.507135,5.653579,2.779712,...,7.646214,0.001095,10.230170,1944.994715,NaN,1.0,200.938091,90.613137,186.841196,128068.500000
std,8.449942,415504.938301,2.677538,7.624659,10706.355022,1.777452,1333.646192,10.666524,10.254535,0.801433,...,2.543281,0.033075,8.949343,28.903691,NaN,0.0,107.947457,122.043969,99.516851,73940.238612
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,1.000000,0.000000,1.000000,1749.000000,NaN,1.0,-1152.680000,-423.080000,-1152.680000,1.000000
25%,3.000000,1000000.000000,3.000000,3.000000,50000.000000,6.000000,0.000000,0.000000,0.000000,2.000000,...,8.000000,0.000000,2.000000,1920.000000,NaN,1.0,137.410000,0.000000,123.580000,64034.750000
50%,9.000000,1000000.000000,6.000000,7.000000,50000.000000,6.000000,0.000000,0.000000,0.000000,3.000000,...,8.000000,0.000000,10.000000,1946.000000,NaN,1.0,189.035000,0.000000,177.390000,128068.500000
75%,14.000000,1000000.000000,6.000000,13.000000,50000.000000,6.000000,0.000000,0.000000,12.450000,3.000000,...,8.000000,0.000000,18.000000,1960.000000,NaN,1.0,248.920000,180.902500,235.090000,192102.250000
max,98.000000,1000000.000000,9.000000,98.000000,100000.000000,9.000000,47500.000000,973.530000,162.610000,7.000000,...,18.000000,1.000000,53.000000,2000.000000,NaN,1.0,4631.860000,1449.240000,4631.860000,256136.000000

In [8]:
print(df.isnull().sum())  # print the number of missing values

QUOTE_DATE             126612
COVER_START             67115
CLAIM3YEARS             66097
P1_EMP_STATUS           67115
P1_PT_EMP_STATUS       254354
                        ...
MTA_DATE               229561
LAST_ANN_PREM_GROSS     66097
POL_STATUS              67115
i                           0
Police                      0
Length: 66, dtype: int64

In [9]:
#df.drop('P1_PT_EMP_STATUS',axis = 1, inplace = True)

In [9]:
for column in df.columns:
  print(f"{column}:{df[column].isnull().sum()}")

QUOTE_DATE:126612
COVER_START:67115
CLAIM3YEARS:66097
P1_EMP_STATUS:67115
P1_PT_EMP_STATUS:254354
BUS_USE:67115
CLERICAL:253192
AD_BUILDINGS:67115
RISK_RATED_AREA_B:115260
SUM_INSURED_BUILDINGS:67115
NCD_GRANTED_YEARS_B:67115
AD_CONTENTS:67115
RISK_RATED_AREA_C:75846
SUM_INSURED_CONTENTS:67115
NCD_GRANTED_YEARS_C:67115
CONTENTS_COVER:67115
BUILDINGS_COVER:67115
SPEC_SUM_INSURED:67115
SPEC_ITEM_PREM:67115
UNSPEC_HRP_PREM:67115
P1_DOB:67115
P1_MAR_STATUS:67115
P1_POLICY_REFUSED:67115
P1_SEX:67115
APPR_ALARM:67115
APPR_LOCKS:67115
BEDROOMS:67115
ROOF_CONSTRUCTION:67115
WALL_CONSTRUCTION:67115
FLOODING:67115
LISTED:67115
MAX_DAYS_UNOCC:67115
NEIGH_WATCH:67115
OCC_STATUS:67115
OWNERSHIP_TYPE:67115
PAYING_GUESTS:67115
PROP_TYPE:67115
SAFE_INSTALLED:67115
SEC_DISC_REQ:67115
SUBSIDENCE:67115
YEARBUILT:67115
CAMPAIGN_DESC:256136
PAYMENT_METHOD:67115
PAYMENT_FREQUENCY:175582
LEGAL_ADDON_PRE_REN:67115
LEGAL_ADDON_POST_REN:67115
HOME_EM_ADDON_PRE_REN:67115
HOME_EM_ADDON_POST_REN:67115
GARDEN_ADDON_PRE_REN:67115
GARDEN_ADDON_POST_REN:67115
KEYCARE_ADDON_PRE_REN:67115
KEYCARE_ADDON_POST_REN:67115
HP1_ADDON_PRE_REN:67115
HP1_ADDON_POST_REN:67115
HP2_ADDON_PRE_REN:67115
HP2_ADDON_POST_REN:67115
HP3_ADDON_PRE_REN:67115
HP3_ADDON_POST_REN:67115
MTA_FLAG:66097
MTA_FAP:200416
MTA_APRP:200416
MTA_DATE:229561
LAST_ANN_PREM_GROSS:66097
POL_STATUS:67115
i:0
Police:0

In [10]:
for column in df.columns:
  if df[column].isnull().sum() > df.shape[0]//2:
    print(f"{column}:{df[column].isnull().sum()}")

P1_PT_EMP_STATUS:254354
CLERICAL:253192
CAMPAIGN_DESC:256136
PAYMENT_FREQUENCY:175582
MTA_FAP:200416
MTA_APRP:200416
MTA_DATE:229561

In [11]:
# Find unique values in the entire DataFrame
unique_values_df = df.apply(pd.Series.nunique)
print(unique_values_df==1)

QUOTE_DATE             False
COVER_START            False
CLAIM3YEARS            False
P1_EMP_STATUS          False
P1_PT_EMP_STATUS       False
                       ...
MTA_DATE               False
LAST_ANN_PREM_GROSS    False
POL_STATUS             False
i                      False
Police                 False
Length: 66, dtype: bool

In [12]:
#df.dropna(inplace=True)
df.isnull().sum()

QUOTE_DATE             126612
COVER_START             67115
CLAIM3YEARS             66097
P1_EMP_STATUS           67115
P1_PT_EMP_STATUS       254354
                        ...
MTA_DATE               229561
LAST_ANN_PREM_GROSS     66097
POL_STATUS              67115
i                           0
Police                      0
Length: 66, dtype: int64

In [13]:
# Check for and drop duplicates
df.drop_duplicates(inplace=True)

In [14]:
[features for features in df.columns if df[features].isnull().sum()>0]

['QUOTE_DATE',
 'COVER_START',
 'CLAIM3YEARS',
 'P1_EMP_STATUS',
 'P1_PT_EMP_STATUS',
 'BUS_USE',
 'CLERICAL',
 'AD_BUILDINGS',
 'RISK_RATED_AREA_B',
 'SUM_INSURED_BUILDINGS',
 'NCD_GRANTED_YEARS_B',
 'AD_CONTENTS',
 'RISK_RATED_AREA_C',
 'SUM_INSURED_CONTENTS',
 'NCD_GRANTED_YEARS_C',
 'CONTENTS_COVER',
 'BUILDINGS_COVER',
 'SPEC_SUM_INSURED',
 'SPEC_ITEM_PREM',
 'UNSPEC_HRP_PREM',
 'P1_DOB',
 'P1_MAR_STATUS',
 'P1_POLICY_REFUSED',
 'P1_SEX',
 'APPR_ALARM',
 'APPR_LOCKS',
 'BEDROOMS',
 'ROOF_CONSTRUCTION',
 'WALL_CONSTRUCTION',
 'FLOODING',
 'LISTED',
 'MAX_DAYS_UNOCC',
 'NEIGH_WATCH',
 'OCC_STATUS',
 'OWNERSHIP_TYPE',
 'PAYING_GUESTS',
 'PROP_TYPE',
 'SAFE_INSTALLED',
 'SEC_DISC_REQ',
 'SUBSIDENCE',
 'YEARBUILT',
 'CAMPAIGN_DESC',
 'PAYMENT_METHOD',
 'PAYMENT_FREQUENCY',
 'LEGAL_ADDON_PRE_REN',
 'LEGAL_ADDON_POST_REN',
 'HOME_EM_ADDON_PRE_REN',
 'HOME_EM_ADDON_POST_REN',
 'GARDEN_ADDON_PRE_REN',
 'GARDEN_ADDON_POST_REN',
 'KEYCARE_ADDON_PRE_REN',
 'KEYCARE_ADDON_POST_REN',
 'HP1_ADDON_PRE_REN',
 'HP1_ADDON_POST_REN',
 'HP2_ADDON_PRE_REN',
 'HP2_ADDON_POST_REN',
 'HP3_ADDON_PRE_REN',
 'HP3_ADDON_POST_REN',
 'MTA_FLAG',
 'MTA_FAP',
 'MTA_APRP',
 'MTA_DATE',
 'LAST_ANN_PREM_GROSS',
 'POL_STATUS']

In [15]:
df.shape

(256136, 66)

In [16]:
df.drop('P1_PT_EMP_STATUS',axis = 1, inplace = True)
df.drop('CLERICAL',axis = 1, inplace = True)
df.drop('CAMPAIGN_DESC',axis = 1, inplace = True)
df.drop('PAYMENT_FREQUENCY',axis = 1, inplace = True)
df.drop('MTA_FAP',axis = 1, inplace = True)
df.drop('MTA_APRP',axis = 1, inplace = True)
df.drop('MTA_DATE',axis = 1, inplace = True)

In [17]:
df.shape

(256136, 59)

In [18]:
df.dropna(inplace=True)

In [19]:
df.shape

(58091, 59)

In [21]:
df.head(10)

,QUOTE_DATE,COVER_START,CLAIM3YEARS,P1_EMP_STATUS,BUS_USE,AD_BUILDINGS,RISK_RATED_AREA_B,SUM_INSURED_BUILDINGS,NCD_GRANTED_YEARS_B,AD_CONTENTS,...,HP1_ADDON_POST_REN,HP2_ADDON_PRE_REN,HP2_ADDON_POST_REN,HP3_ADDON_PRE_REN,HP3_ADDON_POST_REN,MTA_FLAG,LAST_ANN_PREM_GROSS,POL_STATUS,i,Police
0,11/22/2007,22/11/2007,N,R,N,Y,19.0,1000000.0,7.0,Y,...,N,N,N,N,N,N,274.81,Lapsed,1,P000001
1,11/22/2007,01/01/2008,N,E,Y,Y,25.0,1000000.0,6.0,Y,...,N,N,N,N,N,Y,308.83,Live,2,P000002
4,11/22/2007,15/12/2007,N,R,N,Y,5.0,1000000.0,7.0,Y,...,N,N,N,N,N,N,244.58,Live,5,P000005
6,11/19/2007,12/12/2007,N,R,N,Y,1.0,1000000.0,7.0,Y,...,N,N,N,N,N,Y,109.32,Live,7,P000007
8,11/22/2007,01/02/2008,N,E,N,Y,0.0,1000000.0,3.0,Y,...,N,N,Y,N,N,Y,242.16,Live,9,P000009
9,11/22/2007,01/12/2007,N,E,N,Y,5.0,1000000.0,7.0,Y,...,N,N,N,N,N,N,188.31,Live,10,P000010
10,11/22/2007,07/12/2007,N,R,N,Y,1.0,1000000.0,7.0,Y,...,N,N,Y,N,N,Y,97.23,Live,11,P000011
11,11/21/2007,22/12/2007,Y,E,N,Y,8.0,1000000.0,4.0,Y,...,N,N,N,N,N,N,397.42,Live,12,P000012
13,11/27/2007,01/12/2007,N,E,N,Y,1.0,1000000.0,7.0,Y,...,N,N,N,N,N,N,232.06,Live,14,P000014
15,11/23/2007,31/12/2007,N,R,N,Y,0.0,1000000.0,4.0,Y,...,N,N,Y,N,N,Y,316.34,Live,16,P000016